### ISSUE TITLE
Cannot build with a plain pip install or setup.py

### ISSUE THREAD

**Issue by pombredanne** [fireeye/flare-floss#237]
This library depends on other libraries not released on Pypi and cannot be installed using traditional Python tool. The travis build script can help to get this working but it would be great if all deps were on Pypi

**Comment by williballenthin** [comment]
hey @pombredanne thanks for mentioning this. 

to my knowledge, `vivisect` is the only library that's not available on pypi, and this is a conscious choice by its author. while i maintain a minor fork of the library on github, but i'm hesitant to upload the fork to pypi.

its true the building floss is slightly more involved because of this. however, a successful installation typically takes only a single extra step (`pip install https://github.com/williballenthin/vivisect/zipball/master`), which seemed reasonable.

what do you think we can do to improve the situation?

**Comment by pombredanne** [comment]
@williballenthin I think it is perfectly OK for you to release a package on Pypi. You could call it fireeye-vivisect or floss-vivisect and this is a common pattern

**Comment by pombredanne** [comment]
so you decided not to release?

**Comment by williballenthin** [comment]
correct. for the time being (particularly while the issue/question on the upstream vivisect repo is open), i do not want to maintain a fork available on pypi. i realize the installation of floss is therefore slightly more cumbersome, but i think its a reasonable balance.
