### ISSUE TITLE
Can floss be used for finding Chinese Chars?

### ISSUE THREAD

**Issue by bugmeout** [fireeye/flare-floss#251]
I tested this interesting project on windows7 32bit .In IDA Pro,i can find some chinese chars, but this one cannot. I noticed the readme.md said `default mode`, so i wonder if there is an another option for chinese or utf-8 encoded strings?

**Comment by pombredanne** [comment]
Actually rather than "ASCII with interspersed NULL bytes" I would rather say "printable ASCII characters encoded as UTF-16-LE". And "UTF-16-LE" is the way Unicode strings are encoded in Windows PEs.

@bugmeout The difficulty is that detecting Unicode-encoded strings in some arbitrary binary stream is hard unless you have some pattern of sorts that you can identify. Even if you limit yourself to UTF-16-LE, where do you start? How can you find when something is some bona fide UTF string vs. some random garbage?

Even in the simpler case of just detecting if a whole file is text or binary this is not trivial. See for instance this https://github.com/audreyr/binaryornot/blob/9efb669f0c96172f8062388c1710f7be08071a92/binaryornot/helpers.py where I contributed the unicode detection (to avoid detecting unicode-encoded whole text files as binary). This entails using `chardet` which is a heuristic-based encoding detector and various cooking to make a reasonable guess.
