### ISSUE TITLE
Documentation or Python library usage examples?

### ISSUE THREAD

**Issue by cWjL** [fireeye/flare-floss#300]
I've been searching for some usage examples when importing as a Python library.  So far, all I can find is a single example in the repo's issues.  Is there some hidden API documentation or usage examples, or is this left to the user to decipher from the source?

**Comment by williballenthin** [comment]
The FLOSS code can be used as a library; however, there does not exist documentation on how to do this. The best strategy is to review `floss/main.py`, which is the entry point into the command line program.

Internally, we have a couple systems that `import floss; ...` to extract obfuscated strings in an automated workflow; therefore, I know it can be done. However, since we haven't seen overwhelming interest in this externally, we haven't spent the time on documentation. Perhaps we can work together to develop a tutorial?

**Comment by williballenthin** [comment]
ref: https://github.com/fireeye/flare-floss/issues/291#issuecomment-398089011

**Comment by cWjL** [comment]
Ok, great.  Thanks for the response.  I'll go that route.  I can't commit to any tutorial contribution (work schedule is pretty tight), but I'll definitely forward you any info I record.

**Comment by capnspacehook** [comment]
@cWjL if you want you could check out my PR for Cuckoo Sandbox where I integrated Floss into string searching; I came across the same problem you did and took a deep dive into Floss's code to figure out how to call it correctly. https://github.com/cuckoosandbox/cuckoo/pull/2459
