### ISSUE TITLE
File size limitation

### ISSUE THREAD

**Issue by fl380** [fireeye/flare-floss#343]
a very useful tool, unfortunately the target which I'm working is a large file,

> ERROR:floss:FLOSS cannot extract obfuscated strings or stackstrings from files larger than 16777216 bytes

Any plans or suggestions to allow larger files to be analysed?

**Comment by williballenthin** [comment]
we have this limitation in place simply as a sanity check, primarily because code analysis can take quite a while - especially on large files. there's no technical limitation at that file size. 

the check is configured in `floss.const.MAX_FILE_SIZE`. if you're working with capa from master, then you just need to update this file. there's not a way to reconfigure the setting when using the standalone binaries, unfortunately.

**Comment by fl380** [comment]
Thanks for the swift response
